### ISSUE TITLE
Support timeouts for candidates

### ISSUE THREAD

**Issue by bobbytables** [github/scientist#45]
For our use case, we're using Scientist to replace a portion of our application to a separate service. A problem we encountered is that the service we built died, so in our candidate portion of the experiments, the network just waited and eventually timed out, but the page sits for a long time until that point (which is our problem, not a concern of scientist).

So a cool feature would be supporting timeouts in candidates. Thoughts?

**Comment by nthj** [comment]
My initial concern was that if I have candidates with potential timeout issues, I wouldn't want Scientist masking those issues. But Scientist would of course track those as mismatches, so I wouldn't consider those experiments successful. :+1: I like this.

**Comment by seanpoulter** [comment]
It's likely too late to be useful for you @nthj but for anyone else who stumbles across this wanting a timeout, roll it into your experiment or shamefully monkey patch `Scientist::Experiment` with:

```ruby
require 'timeout'

module Scientist::Experiment
  def try_with_timeout(name = nil, timeout, &block)
    Timeout::timeout(timeout) do
      try name, &block
    end
  end
end
```

Ref: [Timeout API on Ruby-Doc](http://ruby-doc.org/stdlib-2.2.3/libdoc/timeout/rdoc/Timeout.html)

**Comment by bobbytables** [comment]
I really think this could take about 10 minutes to make. I'll take a stab at it when I have a chance. Or would love remote pairing if someone wants!

**Comment by jbarnette** [comment]
@bobbytables We've hit issues like that in production too, we often build the timeout into the interface we're testing with a [circuit breaker](https://github.com/jnunemaker/resilient). If the candidate code times out in Scientist, at some point it'll time out in the real world too. 😁 

I'm closing this because I don't think timeouts belong in Scientist proper, but I think it could work as a `scientist-timeout` plugin.
